// ============================================================
// NEW ENGLAND CITIES DATA — 5 STATES
// Connecticut, Rhode Island, New Hampshire, Vermont, Maine
// ============================================================

import { CityData } from "./cities-data";

// ─── CONNECTICUT ────────────────────────────────────────────
export const CONNECTICUT_CITIES: CityData[] = [
  {
    slug: "hartford-ct",
    name: "Hartford",
    zipCodes: ["06101","06102","06103","06104","06105","06106","06107","06108","06109","06110","06111","06112","06114","06115","06117","06118","06119","06120","06123","06126","06127","06128","06129","06131","06132","06133","06134","06137","06138","06141","06142","06143","06144","06145","06146","06147","06150","06151","06152","06153","06154","06155","06156","06160","06161","06167","06176","06180","06183","06199"],
    county: "Hartford County",
    region: "Greater Hartford",
    population: 121054,
    lat: 41.7637,
    lng: -72.6851,
    metaTitle: "Ice Cream Truck Rental in Hartford, CT | American Legend | Book Now",
    metaDescription: "Premium ice cream truck catering in Hartford, CT. Serving all Hartford neighborhoods for birthdays, corporate events, weddings. Get a free quote!",
    heroHeadline: "Hartford's Premier Ice Cream Truck",
    heroSubline: "Bringing legendary frozen treats to Hartford, CT events — birthdays, corporate days, weddings, and every celebration across the Capital City.",
    localIntro: "American Legend Ice Cream Truck proudly serves Hartford, Connecticut's capital and largest city. From Asylum Hill to West End, we bring premium ice cream directly to your event.",
    neighborhoods: ["Asylum Hill","West End","South Green","Barry Square","Frog Hollow","Blue Hills","Northeast","Parkville","Upper Albany"],
    nearbyAreas: ["West Hartford","Newington","Wethersfield","East Hartford","Windsor"],
    landmarkMentions: ["Bushnell Park","Connecticut State Capitol","Mark Twain House"],
    localFAQs: [
      { question: "Do you serve ice cream trucks in Hartford, CT?", answer: "Yes! American Legend serves all Hartford neighborhoods and the surrounding Greater Hartford area." },
      { question: "How much does an ice cream truck rental cost in Hartford?", answer: "Our packages start at 190 dollars. Contact us for a custom Hartford quote." },
    ],
    heroImageQuery: "cinematic ice cream truck Hartford Connecticut golden hour event celebration",
    tier: 1, isTopCity: true, priorityScore: 90,
  },
  {
    slug: "new-haven-ct",
    name: "New Haven",
    zipCodes: ["06501","06502","06503","06504","06505","06506","06507","06508","06509","06510","06511","06512","06513","06514","06515","06516","06517","06518","06519","06520","06521","06525"],
    county: "New Haven County",
    region: "Greater New Haven",
    population: 130250,
    lat: 41.3083,
    lng: -72.9279,
    metaTitle: "Ice Cream Truck Rental in New Haven, CT | American Legend | Book Now",
    metaDescription: "Premium ice cream truck catering in New Haven, CT. Perfect for Yale events, birthdays, corporate gatherings. Get a free quote today!",
    heroHeadline: "New Haven's Favorite Ice Cream Truck",
    heroSubline: "From Yale's campus to East Rock and Westville — American Legend brings legendary ice cream catering to every New Haven event.",
    localIntro: "New Haven is a vibrant city full of celebrations, and American Legend Ice Cream Truck is here to make every event sweeter.",
    neighborhoods: ["East Rock","Westville","Wooster Square","Fair Haven","The Hill","Dwight","Beaver Hills","Newhallville"],
    nearbyAreas: ["West Haven","Hamden","East Haven","North Haven","Milford"],
    landmarkMentions: ["Yale University","New Haven Green","Wooster Square"],
    localFAQs: [
      { question: "Do you serve Yale University events in New Haven?", answer: "Absolutely! We love serving Yale campus events, graduation parties, and corporate events in New Haven." },
    ],
    heroImageQuery: "cinematic ice cream truck New Haven Connecticut Yale golden hour celebration",
    tier: 1, isTopCity: true, priorityScore: 88,
  },
  {
    slug: "stamford-ct",
    name: "Stamford",
    zipCodes: ["06901","06902","06903","06904","06905","06906","06907","06910","06911","06912","06913","06914","06920","06921","06922","06926","06927"],
    county: "Fairfield County",
    region: "Coastal Connecticut",
    population: 135470,
    lat: 41.0534,
    lng: -73.5387,
    metaTitle: "Ice Cream Truck Rental in Stamford, CT | American Legend",
    metaDescription: "Premium ice cream truck catering in Stamford, CT. Corporate events, birthday parties, and weddings. Book American Legend today!",
    heroHeadline: "Stamford's Luxury Ice Cream Truck Experience",
    heroSubline: "American Legend brings premium ice cream catering to Stamford's corporate campuses, neighborhoods, and special events.",
    localIntro: "Stamford is Connecticut's business hub, and American Legend brings the same premium, professional experience to every Stamford corporate event, birthday, and celebration.",
    nearbyAreas: ["Greenwich","Darien","Norwalk","New Canaan","Westport"],
    localFAQs: [
      { question: "Do you serve corporate events in Stamford?", answer: "Yes! We specialize in corporate employee appreciation days and company picnics in Stamford." },
    ],
    heroImageQuery: "cinematic ice cream truck Stamford Connecticut corporate event golden hour",
    tier: 1, isTopCity: true, priorityScore: 86,
  },
  {
    slug: "bridgeport-ct",
    name: "Bridgeport",
    zipCodes: ["06601","06602","06604","06605","06606","06607","06608","06610"],
    county: "Fairfield County",
    region: "Coastal Connecticut",
    population: 148654,
    lat: 41.1865,
    lng: -73.1952,
    metaTitle: "Ice Cream Truck Rental in Bridgeport, CT | American Legend",
    metaDescription: "Ice cream truck catering in Bridgeport, CT. Birthday parties, corporate events, and community celebrations. Book American Legend today!",
    heroHeadline: "Bridgeport's Premier Ice Cream Truck Catering",
    heroSubline: "Serving Bridgeport, CT with legendary frozen treats for every occasion.",
    localIntro: "American Legend serves all of Bridgeport, Connecticut's largest city by population, with premium ice cream truck catering for events of all sizes.",
    nearbyAreas: ["Stratford","Milford","Trumbull","Shelton","Derby"],
    localFAQs: [
      { question: "Do you serve Bridgeport, CT?", answer: "Yes! We serve all of Bridgeport and Fairfield County." },
    ],
    heroImageQuery: "cinematic ice cream truck Bridgeport Connecticut summer event celebration",
    tier: 2, isTopCity: true, priorityScore: 82,
  },
  {
    slug: "greenwich-ct",
    name: "Greenwich",
    zipCodes: ["06830","06831","06832","06836","06870","06878","06879","06880","06896","06897"],
    county: "Fairfield County",
    region: "Coastal Connecticut",
    population: 63518,
    lat: 41.0262,
    lng: -73.6282,
    metaTitle: "Luxury Ice Cream Truck Rental in Greenwich, CT | American Legend",
    metaDescription: "Premium ice cream truck catering in Greenwich, CT. Serving Back Country, Old Greenwich, and Cos Cob for weddings, galas, and upscale events.",
    heroHeadline: "Greenwich's Luxury Ice Cream Experience",
    heroSubline: "American Legend brings an upscale ice cream truck experience to Greenwich's most exclusive estates and events.",
    localIntro: "Greenwich is Connecticut's most prestigious community, and American Legend delivers a matching level of luxury and professionalism to every event.",
    neighborhoods: ["Old Greenwich","Cos Cob","Riverside","Byram","Back Country","Glenville"],
    nearbyAreas: ["Stamford","Darien","New Canaan","Port Chester NY","Rye NY"],
    localFAQs: [
      { question: "Do you serve estate events in Greenwich Back Country?", answer: "Yes! We specialize in upscale private events throughout Greenwich, including Back Country." },
    ],
    heroImageQuery: "cinematic luxury ice cream truck Greenwich Connecticut estate event golden hour",
    tier: 1, isTopCity: true, priorityScore: 85,
  },
  {
    slug: "norwalk-ct",
    name: "Norwalk",
    zipCodes: ["06850","06851","06852","06853","06854","06855","06856","06857","06858","06860"],
    county: "Fairfield County",
    region: "Coastal Connecticut",
    population: 91184,
    lat: 41.1176,
    lng: -73.4082,
    metaTitle: "Ice Cream Truck Rental in Norwalk, CT | American Legend",
    metaDescription: "Premium ice cream truck catering in Norwalk, CT. Birthdays, weddings, corporate events. Get a free quote!",
    heroHeadline: "Norwalk's Premier Ice Cream Truck",
    heroSubline: "Serving SoNo, Rowayton, and all of Norwalk with legendary ice cream catering.",
    localIntro: "American Legend serves all of Norwalk, CT including South Norwalk (SoNo), Rowayton, and East Norwalk with premium mobile ice cream catering.",
    nearbyAreas: ["Westport","Darien","Stamford","Wilton","New Canaan"],
    localFAQs: [
      { question: "Do you serve Norwalk and SoNo events?", answer: "Absolutely! We serve all Norwalk neighborhoods including SoNo, Rowayton, and East Norwalk." },
    ],
    heroImageQuery: "cinematic ice cream truck Norwalk Connecticut coastal summer event",
    tier: 2, isTopCity: true, priorityScore: 75,
  },
];

// ─── RHODE ISLAND ───────────────────────────────────────────
export const RHODE_ISLAND_CITIES: CityData[] = [
  {
    slug: "providence-ri",
    name: "Providence",
    zipCodes: ["02901","02902","02903","02904","02905","02906","02907","02908","02909","02910","02911","02912","02918","02940"],
    county: "Providence County",
    region: "Greater Providence",
    population: 190934,
    lat: 41.8240,
    lng: -71.4128,
    metaTitle: "Ice Cream Truck Rental in Providence, RI | American Legend | Book Now",
    metaDescription: "Premium ice cream truck catering in Providence, RI. Serving College Hill, Federal Hill, and all Providence neighborhoods. Get a free quote!",
    heroHeadline: "Providence's Premier Ice Cream Truck",
    heroSubline: "From College Hill to Federal Hill — American Legend brings legendary ice cream catering to every Providence celebration.",
    localIntro: "American Legend proudly serves Providence, Rhode Island's vibrant capital city. Whether it's a Brown University event on College Hill, a birthday in Fox Point, or a corporate gathering downtown, we bring premium ice cream directly to your venue.",
    neighborhoods: ["College Hill","Federal Hill","Fox Point","Elmwood","Mount Pleasant","Smith Hill","Valley","Olneyville","Wanskuck"],
    nearbyAreas: ["Cranston","Pawtucket","North Providence","Johnston","East Providence"],
    landmarkMentions: ["WaterFire","Providence River","Roger Williams Park","Brown University"],
    localFAQs: [
      { question: "Do you serve Brown University events in Providence?", answer: "Yes! We love serving college events, graduation parties, and campus celebrations in Providence." },
    ],
    heroImageQuery: "cinematic ice cream truck Providence Rhode Island golden hour WaterFire river celebration",
    tier: 1, isTopCity: true, priorityScore: 92,
  },
  {
    slug: "newport-ri",
    name: "Newport",
    zipCodes: ["02840","02841","02842"],
    county: "Newport County",
    region: "Coastal Rhode Island",
    population: 24672,
    lat: 41.4901,
    lng: -71.3128,
    metaTitle: "Luxury Ice Cream Truck Rental in Newport, RI | American Legend",
    metaDescription: "Premium ice cream truck catering in Newport, RI. Perfect for mansion events, weddings, corporate gatherings, and summer celebrations.",
    heroHeadline: "Newport's Luxury Ice Cream Experience",
    heroSubline: "American Legend brings legendary frozen treats to Newport's most exclusive estates, yacht clubs, and waterfront celebrations.",
    localIntro: "Newport is one of New England's most iconic destinations, and American Legend delivers an ice cream truck experience that matches its grandeur.",
    neighborhoods: ["Bellevue Avenue","Thames Street","5th Ward","Kay/Catherine","The Point"],
    nearbyAreas: ["Middletown","Portsmouth","Jamestown","Bristol","Narragansett"],
    landmarkMentions: ["The Breakers","Cliff Walk","Newport Mansions","Bellevue Avenue"],
    localFAQs: [
      { question: "Do you serve mansion and estate events in Newport?", answer: "Absolutely! We specialize in upscale private events at Newport's historic mansions and waterfront venues." },
    ],
    heroImageQuery: "cinematic luxury ice cream truck Newport Rhode Island mansion waterfront golden hour wedding",
    tier: 1, isTopCity: true, priorityScore: 88,
  },
  {
    slug: "warwick-ri",
    name: "Warwick",
    zipCodes: ["02886","02887","02888","02889"],
    county: "Kent County",
    region: "Rhode Island",
    population: 82672,
    lat: 41.7001,
    lng: -71.4162,
    metaTitle: "Ice Cream Truck Rental in Warwick, RI | American Legend",
    metaDescription: "Ice cream truck catering in Warwick, RI. Birthday parties, corporate events more. Book American Legend today!",
    heroHeadline: "Warwick's Favorite Ice Cream Truck",
    heroSubline: "Serving all Warwick neighborhoods with premium ice cream catering for every celebration.",
    localIntro: "American Legend serves all of Warwick, Rhode Island's second-largest city, with professional mobile ice cream catering.",
    nearbyAreas: ["Cranston","East Greenwich","North Kingstown","Providence","West Warwick"],
    localFAQs: [
      { question: "Do you serve Warwick, RI events?", answer: "Yes! We serve all of Warwick and Kent County." },
    ],
    heroImageQuery: "cinematic ice cream truck Warwick Rhode Island summer event celebration",
    tier: 2, isTopCity: true, priorityScore: 78,
  },
];

// ─── NEW HAMPSHIRE ──────────────────────────────────────────
export const NEW_HAMPSHIRE_CITIES: CityData[] = [
  {
    slug: "manchester-nh",
    name: "Manchester",
    zipCodes: ["03101","03102","03103","03104","03105","03106","03107","03108","03109","03111"],
    county: "Hillsborough County",
    region: "Southern New Hampshire",
    population: 115644,
    lat: 42.9956,
    lng: -71.4548,
    metaTitle: "Ice Cream Truck Rental in Manchester, NH | American Legend | Book Now",
    metaDescription: "Premium ice cream truck catering in Manchester, NH. Serving all Manchester neighborhoods for birthdays, corporate events. Get a free quote!",
    heroHeadline: "Manchester's Premier Ice Cream Truck",
    heroSubline: "Bringing legendary frozen treats to Manchester, NH for every celebration.",
    localIntro: "American Legend proudly serves Manchester, New Hampshire's largest city with premium mobile ice cream catering.",
    nearbyAreas: ["Nashua","Concord","Bedford","Goffstown","Hooksett"],
    localFAQs: [
      { question: "Do you serve Manchester, NH events?", answer: "Yes! We serve all of Manchester and southern New Hampshire." },
    ],
    heroImageQuery: "cinematic ice cream truck Manchester New Hampshire summer event celebration",
    tier: 1, isTopCity: true, priorityScore: 88,
  },
  {
    slug: "nashua-nh",
    name: "Nashua",
    zipCodes: ["03060","03061","03062","03063","03064"],
    county: "Hillsborough County",
    region: "Southern New Hampshire",
    population: 91322,
    lat: 42.7654,
    lng: -71.4676,
    metaTitle: "Ice Cream Truck Rental in Nashua, NH | American Legend",
    metaDescription: "Premium ice cream truck catering in Nashua, NH. Book American Legend for birthdays, corporate events, and celebrations!",
    heroHeadline: "Nashua's Favorite Ice Cream Truck",
    heroSubline: "Serving all Nashua neighborhoods with premium ice cream catering for every occasion.",
    localIntro: "American Legend serves Nashua, NH with professional mobile ice cream catering for events of all sizes.",
    nearbyAreas: ["Manchester","Merrimack","Hudson","Milford","Amherst"],
    localFAQs: [
      { question: "Do you serve Nashua, NH events?", answer: "Yes! We serve all of Nashua and surrounding Hillsborough County." },
    ],
    heroImageQuery: "cinematic ice cream truck Nashua New Hampshire summer celebration",
    tier: 1, isTopCity: true, priorityScore: 84,
  },
  {
    slug: "portsmouth-nh",
    name: "Portsmouth",
    zipCodes: ["03801","03802","03803","03804"],
    county: "Rockingham County",
    region: "Seacoast New Hampshire",
    population: 21956,
    lat: 43.0718,
    lng: -70.7626,
    metaTitle: "Ice Cream Truck Rental in Portsmouth, NH | American Legend",
    metaDescription: "Premium ice cream truck catering in Portsmouth, NH. Perfect for waterfront events, weddings, and summer celebrations on the Seacoast.",
    heroHeadline: "Portsmouth's Premium Ice Cream Truck",
    heroSubline: "Serving Portsmouth's historic waterfront, Market Square, and surrounding Seacoast communities.",
    localIntro: "Portsmouth is one of New England's most charming coastal cities, and American Legend delivers a matching premium ice cream experience for every event.",
    nearbyAreas: ["Rye","Newington","Greenland","Exeter","Hampton"],
    landmarkMentions: ["Market Square","Prescott Park","Portsmouth Harbor","Strawbery Banke"],
    localFAQs: [
      { question: "Do you serve waterfront events in Portsmouth, NH?", answer: "Yes! We love serving Portsmouth's beautiful waterfront events and festivals." },
    ],
    heroImageQuery: "cinematic ice cream truck Portsmouth New Hampshire historic waterfront summer celebration",
    tier: 2, isTopCity: true, priorityScore: 80,
  },
];

// ─── VERMONT ─────────────────────────────────────────────────
export const VERMONT_CITIES: CityData[] = [
  {
    slug: "burlington-vt",
    name: "Burlington",
    zipCodes: ["05401","05402","05403","05404","05405","05406","05407","05408"],
    county: "Chittenden County",
    region: "Northwestern Vermont",
    population: 45012,
    lat: 44.4759,
    lng: -73.2121,
    metaTitle: "Ice Cream Truck Rental in Burlington, VT | American Legend | Book Now",
    metaDescription: "Premium ice cream truck catering in Burlington, VT. Serving UVM events, Church Street celebrations, and all Burlington events. Get a free quote!",
    heroHeadline: "Burlington's Premier Ice Cream Truck",
    heroSubline: "Bringing legendary frozen treats to Burlington, Vermont's most vibrant city for every season and celebration.",
    localIntro: "American Legend serves Burlington, Vermont's largest city and home to the University of Vermont. From Church Street Marketplace festivals to lakefront events on Waterfront Park, we bring premium ice cream catering to every Burlington celebration.",
    neighborhoods: ["Hill Section","New North End","Old North End","South End","Downtown","Centennial"],
    nearbyAreas: ["South Burlington","Winooski","Williston","Colchester","Essex"],
    landmarkMentions: ["Church Street Marketplace","Waterfront Park","Lake Champlain","University of Vermont"],
    localFAQs: [
      { question: "Do you serve UVM events in Burlington?", answer: "Yes! We love serving University of Vermont events, graduation parties, and campus celebrations." },
    ],
    heroImageQuery: "cinematic ice cream truck Burlington Vermont Lake Champlain golden hour summer event",
    tier: 1, isTopCity: true, priorityScore: 85,
  },
  {
    slug: "stowe-vt",
    name: "Stowe",
    zipCodes: ["05672"],
    county: "Lamoille County",
    region: "Northern Vermont",
    population: 5082,
    lat: 44.4654,
    lng: -72.6874,
    metaTitle: "Ice Cream Truck Rental in Stowe, VT | American Legend",
    metaDescription: "Luxury ice cream truck catering in Stowe, VT. Perfect for resort events, weddings, and Vermont mountain celebrations.",
    heroHeadline: "Stowe's Luxury Ice Cream Experience",
    heroSubline: "American Legend brings premium ice cream catering to Stowe's world-class resorts and mountain celebrations.",
    localIntro: "Stowe is Vermont's most celebrated resort destination, and American Legend delivers a premium ice cream experience that matches its reputation.",
    nearbyAreas: ["Morrisville","Waterbury","Johnson","Hyde Park","Jeffersonville"],
    landmarkMentions: ["Stowe Mountain Resort","Von Trapp Family Lodge","Mount Mansfield"],
    localFAQs: [
      { question: "Do you serve resort events in Stowe?", answer: "Yes! We serve Stowe Mountain Resort events, Von Trapp Lodge celebrations, and private estate gatherings." },
    ],
    heroImageQuery: "cinematic luxury ice cream truck Stowe Vermont mountain resort golden hour autumn event",
    tier: 2, isTopCity: true, priorityScore: 78,
  },
];

// ─── MAINE ───────────────────────────────────────────────────
export const MAINE_CITIES: CityData[] = [
  {
    slug: "portland-me",
    name: "Portland",
    zipCodes: ["04101","04102","04103","04104","04105","04106","04107","04108","04109","04110","04112","04116","04122","04123","04124"],
    county: "Cumberland County",
    region: "Southern Maine",
    population: 68408,
    lat: 43.6591,
    lng: -70.2568,
    metaTitle: "Ice Cream Truck Rental in Portland, ME | American Legend | Book Now",
    metaDescription: "Premium ice cream truck catering in Portland, ME. Serving the Old Port, East Bayside, and all Portland, Maine events. Get a free quote!",
    heroHeadline: "Portland Maine's Premier Ice Cream Truck",
    heroSubline: "Bringing legendary frozen treats to Portland's Old Port, Munjoy Hill, and every corner of Maine's most vibrant city.",
    localIntro: "American Legend serves Portland, Maine — New England's most beloved coastal city. From Old Port festivals to Munjoy Hill events and corporate gatherings downtown, we bring premium ice cream catering to every Portland celebration.",
    neighborhoods: ["Old Port","Munjoy Hill","West End","Deering","East Bayside","Woodfords","Stroudwater"],
    nearbyAreas: ["South Portland","Westbrook","Scarborough","Cape Elizabeth","Falmouth"],
    landmarkMentions: ["Old Port","Portland Head Light","Casco Bay","Eastern Promenade","Maine State Pier"],
    localFAQs: [
      { question: "Do you serve Old Port events in Portland, ME?", answer: "Yes! Portland's Old Port is one of our favorite event destinations. We serve festivals, private events, and more." },
    ],
    heroImageQuery: "cinematic ice cream truck Portland Maine Old Port lighthouse coastal golden hour summer celebration",
    tier: 1, isTopCity: true, priorityScore: 90,
  },
  {
    slug: "kennebunkport-me",
    name: "Kennebunkport",
    zipCodes: ["04046"],
    county: "York County",
    region: "Southern Maine Coast",
    population: 3474,
    lat: 43.3626,
    lng: -70.4773,
    metaTitle: "Luxury Ice Cream Truck Rental in Kennebunkport, ME | American Legend",
    metaDescription: "Premium ice cream truck catering in Kennebunkport, ME. Perfect for coastal weddings, estate events, and upscale summer celebrations.",
    heroHeadline: "Kennebunkport's Luxury Ice Cream Experience",
    heroSubline: "American Legend brings legendary ice cream catering to Kennebunkport's most exclusive waterfront estates and summer celebrations.",
    localIntro: "Kennebunkport is one of Maine's most prestigious resort communities, and American Legend delivers a premium ice cream truck experience — from waterfront estate weddings to Dock Square summer events.",
    nearbyAreas: ["Kennebunk","Wells","Arundel","Biddeford","Saco"],
    landmarkMentions: ["Dock Square","Ocean Avenue","Cape Porpoise","Walker's Point"],
    localFAQs: [
      { question: "Do you serve estate weddings in Kennebunkport?", answer: "Yes! Kennebunkport is a top destination for luxury weddings and we specialize in upscale private events." },
    ],
    heroImageQuery: "cinematic luxury ice cream truck Kennebunkport Maine coastal waterfront estate golden hour wedding",
    tier: 2, isTopCity: true, priorityScore: 80,
  },
  {
    slug: "bangor-me",
    name: "Bangor",
    zipCodes: ["04401","04402"],
    county: "Penobscot County",
    region: "Central Maine",
    population: 31753,
    lat: 44.8012,
    lng: -68.7778,
    metaTitle: "Ice Cream Truck Rental in Bangor, ME | American Legend",
    metaDescription: "Ice cream truck catering in Bangor, ME. Birthday parties, corporate events, and community celebrations in central Maine.",
    heroHeadline: "Bangor Maine's Ice Cream Truck",
    heroSubline: "Serving all of Bangor, ME with legendary ice cream catering for every celebration.",
    localIntro: "American Legend serves Bangor, Maine's third-largest city and the gateway to the Maine wilderness, with premium mobile ice cream catering.",
    nearbyAreas: ["Brewer","Orono","Veazie","Hampden","Old Town"],
    localFAQs: [
      { question: "Do you serve Bangor, ME events?", answer: "Yes! We serve Bangor and central Maine. Contact us for distance-specific pricing." },
    ],
    heroImageQuery: "cinematic ice cream truck Bangor Maine river summer event celebration",
    tier: 2, isTopCity: true, priorityScore: 72,
  },
];

// ─── ALL NEW ENGLAND CITIES COMBINED ────────────────────────
export const NEW_ENGLAND_CITIES: CityData[] = [
  ...CONNECTICUT_CITIES,
  ...RHODE_ISLAND_CITIES,
  ...NEW_HAMPSHIRE_CITIES,
  ...VERMONT_CITIES,
  ...MAINE_CITIES,
];

// ─── ALL CITIES (MA + New England) ───────────────────────────
export const NEW_ENGLAND_STATES = [
  { code: "MA", name: "Massachusetts", slug: "massachusetts", capital: "Boston", color: "#071B3A" },
  { code: "CT", name: "Connecticut", slug: "connecticut", capital: "Hartford", color: "#1B4F72" },
  { code: "RI", name: "Rhode Island", slug: "rhode-island", capital: "Providence", color: "#922B21" },
  { code: "NH", name: "New Hampshire", slug: "new-hampshire", capital: "Concord", color: "#1E8449" },
  { code: "VT", name: "Vermont", slug: "vermont", capital: "Montpelier", color: "#6E2F0A" },
  { code: "ME", name: "Maine", slug: "maine", capital: "Augusta", color: "#154360" },
];
